### PR TITLE
Fixes the documentation and examples of the append methods

### LINKED ISSUE #163: Wrong code sample on the append method
The following documentation uses a code sample that doesn't show how to use the `append` method.

https://docs.rs/heed/0.20.0-alpha.0/heed/struct.Database.html#method.append

### PR DESCRIPTION
**Pull request by darnuria**
Now documentation of KeyExist Error describe the case of append with unordered data.

Also change the examples to use the append function.

## Related issue
Fixes #163

## PR checklist

Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

File: heed/src/mdb/lmdb_error.rs [hunk 1]
```diff
@@ -10,6 +10,9 @@ use lmdb_master_sys as ffi;
 #[derive(Debug, Copy, Clone, Eq, PartialEq)]
 pub enum Error {
     /// key/data pair already exists.
+    ///
+    /// May be also returned by appends functions are passed a data
+    /// that don't respect the database ordering.
```
Comment (Kerollmops) [inline heed/src/mdb/lmdb_error.rs:15]:
```suggestion
    /// May also be returned by the `append` iterator methods when the appended key
    /// doesn't respect the database ordering.
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]

**Comment by Kerollmops** [comment]
Thank you very much ❤️

**Comment by darnuria** [comment]
Thanks for the review and your time!
